### ISSUE TITLE
How many pool create in application?

### ISSUE THREAD

**Issue by hanh45** [DarkPhoenixs/connection-pool-client#1]
Hi team,
I search for pool of kafka client and i found the source code of you.
I confuse about this connection pool:
Ex:
I have one java project. In this project, i want a pool (only one pool) of kafka producer. 
I have 2 java class with init kafka pool as:

Class 1:
```
PoolConfig config = new PoolConfig();
...
Properties props = new Properties();
....
/* connection pool */
KafkaConnectionPool pool = new KafkaConnectionPool(config, props);
```

Class 2:
```
PoolConfig config = new PoolConfig();
...
Properties props = new Properties();
....
/* connection pool */
KafkaConnectionPool pool = new KafkaConnectionPool(config, props);
```

How many pool objects created?

Thanks,
Hanh45

**Comment by VictorZeng** [comment]
Create one `KafkaConnectionPool` only one pool in your project.

**Comment by hanh45** [comment]
Hi @VictorZeng ,

I confuse with function ```initPool``` in ```abstract class PoolBase<T>```
```
protected void initPool(final GenericObjectPoolConfig poolConfig, PooledObjectFactory<T> factory) {
		if (this.internalPool != null)
			this.destroy();

		this.internalPool = new GenericObjectPool<T>(factory, poolConfig);
	}
```
With my example above, when class 2 call ``new KafkaConnectionPool``, pool of class 1 is destroy() ?

Thanks for explain!

**Comment by VictorZeng** [comment]
@hanh45 This is impossible, there are two KafkaConnectionPool object in the JVM, class 1 don't destroy().

**Comment by VictorZeng** [comment]
@hanh45 With your example above, create 2 pool objects in your project.

**Comment by hanh45** [comment]
Hi @VictorZeng ,

I understand, when parent class new ```new KafkaConnectionPool```, the child class's project reference that variable from parent class => only one pool create. (as model: producer/consumer)

I researching for a common pool, that class's project can call pool every where.

Thanks again for explain!
